[[pages]]
name = "Home"
path = "main.py"
icon = "ğŸ "

[[pages]]
name = "Processar Dados"
path = "pages/01_processar_dados.py"
icon = "ğŸ“Š"

[[pages]]
name = "Gerar ColeÃ§Ã£o"
path = "pages/02_gerar_colecao.py"
icon = "ğŸ“‹"