[[pages]]
path = "main.py"
name = " Início"
icon = ""

[[pages]]
name = " Processamento"
icon = ""
is_section = true

[[pages]]
path = "pages/01_processar_dados.py"
name = "1 Processar Planilha"
icon = ""

[[pages]]
path = "pages/02_gerar_colecao.py"
name = "2 Gerar Coleção Postman"
icon = ""

[[pages]]
name = " Gerenciamento"
icon = ""
is_section = true

[[pages]]
path = "pages/03_editor_planilhas.py"
name = " Editor de Planilhas"
icon = ""
